@startuml
!theme cyborg-outline

class Counter {
    - int count

    + Counter()
    + int getCount()
    + void increment()
    + void decrement()
}

class MultipleCounter extends Counter {
    - int times
    + MultipleCounter()
}

@enduml
